# Generated by Django 5.1.1 on 2024-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='firstname',
            field=models.CharField(default='DefaultFirstName', max_length=150),
        ),
        migrations.AddField(
            model_name='admin',
            name='lastname',
            field=models.CharField(default='DefaultLastName', max_length=150),
        ),
    ]
