# Generated by Django 5.1.1 on 2024-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_firstname_alter_admin_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
