# Generated by Django 5.1.2 on 2024-11-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_alter_order_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
